---
- name: Gather service facts
  ansible.builtin.service_facts:

- name: Check nginx is running
  ansible.builtin.assert:
    that:
      - ansible_facts.services['nginx.service'].state == 'running'
    success_msg: "nginx is running"
    fail_msg: "nginx is NOT running"

- name: Check HTTP on port 80
  ansible.builtin.uri:
    url: http://localhost
    return_content: false
    status_code: 200
  register: validate_http80

- name: Check HTTP on port 8080
  ansible.builtin.uri:
    url: http://localhost:8080
    return_content: false
    status_code: 200
  register: validate_http8080

- name: Print validation report
  ansible.builtin.debug:
    msg:
      - "Host:               {{ inventory_hostname }}"
      - "nginx:              {{ ansible_facts.services['nginx.service'].state }}"
      - "HTTP :80           {{ validate_http80.status }}"
      - "HTTP :8080         {{ validate_http8080.status }}"
